<a href="https://colab.research.google.com/github/s104004504/aaa123/blob/master/A040E117_5_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
print("pandas version: %s" % pd.__version__)
import matplotlib
print("matplotlib version: %s" % matplotlib.__version__)
import numpy as np
print("numpy version: %s" % np.__version__)
import sklearn
print("scikit-learn version: %s" % sklearn.__version__)

pandas version: 0.24.2
matplotlib version: 3.0.3
numpy version: 1.16.3
scikit-learn version: 0.20.3


In [5]:
import numpy as np
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
print(x)

[[1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j]]


In [6]:
import numpy as np
x = np. zeros((2, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
import numpy as np
y = np.arange(2, 3, 0.1) # start, end, step
print(y)

[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [10]:
import numpy as np
z = np.linspace(1., 4., 6) # start, end, num
print(z)

[1.  1.6 2.2 2.8 3.4 4. ]


In [9]:
import numpy as np
w = np.indices((3, 3))
print(w)

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [14]:
### 作業1 ###
import numpy as np
x = np.linspace(2.0, 3.0, num=5)
y = np.linspace(2.0, 3.0, num=5, endpoint=False)
z = np.linspace(2.0, 3.0, num=5, retstep=True)
print(x)
print(y)
print(z)

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


In [15]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]]) # 2D array
print(ar2)

[[0 3 5]
 [2 8 7]]


In [16]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [21]:

x2.reshape(4,1)
x

array([0, 1, 2, 3])

In [23]:
x2.shape

(4, 1)

In [27]:
import numpy as np

a=np.array([[0,1],[2,3]])

a.reshape(1,4)
a.reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

In [28]:
### 作業2 ###
import numpy as np
x = np.arange(2,10).reshape(2,4)
x

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [37]:
### 作業3 ###
import numpy as np
ar = np.arange(1,5)
ar.prod()

24